// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sincin-v/collector/internal/service (interfaces: MetricStorage)

// Package mock_service is a generated GoMock package.
package storage

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/sincin-v/collector/internal/models"
)

// MockMetricStorage is a mock of MetricStorage interface.
type MockMetricStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMetricStorageMockRecorder
}

// MockMetricStorageMockRecorder is the mock recorder for MockMetricStorage.
type MockMetricStorageMockRecorder struct {
	mock *MockMetricStorage
}

// NewMockMetricStorage creates a new mock instance.
func NewMockMetricStorage(ctrl *gomock.Controller) *MockMetricStorage {
	mock := &MockMetricStorage{ctrl: ctrl}
	mock.recorder = &MockMetricStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricStorage) EXPECT() *MockMetricStorageMockRecorder {
	return m.recorder
}

// GetAllCountersMetrics mocks base method.
func (m *MockMetricStorage) GetAllCountersMetrics(arg0 context.Context) map[string]int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCountersMetrics", arg0)
	ret0, _ := ret[0].(map[string]int64)
	return ret0
}

// GetAllCountersMetrics indicates an expected call of GetAllCountersMetrics.
func (mr *MockMetricStorageMockRecorder) GetAllCountersMetrics(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCountersMetrics", reflect.TypeOf((*MockMetricStorage)(nil).GetAllCountersMetrics), arg0)
}

// GetAllGaugeMetrics mocks base method.
func (m *MockMetricStorage) GetAllGaugeMetrics(arg0 context.Context) map[string]float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllGaugeMetrics", arg0)
	ret0, _ := ret[0].(map[string]float64)
	return ret0
}

// GetAllGaugeMetrics indicates an expected call of GetAllGaugeMetrics.
func (mr *MockMetricStorageMockRecorder) GetAllGaugeMetrics(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGaugeMetrics", reflect.TypeOf((*MockMetricStorage)(nil).GetAllGaugeMetrics), arg0)
}

// GetMetric mocks base method.
func (m *MockMetricStorage) GetMetric(arg0 context.Context, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetric", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetric indicates an expected call of GetMetric.
func (mr *MockMetricStorageMockRecorder) GetMetric(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetric", reflect.TypeOf((*MockMetricStorage)(nil).GetMetric), arg0, arg1, arg2)
}

// HealthCheck mocks base method.
func (m *MockMetricStorage) HealthCheck(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockMetricStorageMockRecorder) HealthCheck(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockMetricStorage)(nil).HealthCheck), arg0)
}

// UpdateCounterMetric mocks base method.
func (m *MockMetricStorage) UpdateCounterMetric(arg0 context.Context, arg1 string, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCounterMetric", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCounterMetric indicates an expected call of UpdateCounterMetric.
func (mr *MockMetricStorageMockRecorder) UpdateCounterMetric(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCounterMetric", reflect.TypeOf((*MockMetricStorage)(nil).UpdateCounterMetric), arg0, arg1, arg2)
}

// UpdateGaugeMetric mocks base method.
func (m *MockMetricStorage) UpdateGaugeMetric(arg0 context.Context, arg1 string, arg2 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGaugeMetric", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGaugeMetric indicates an expected call of UpdateGaugeMetric.
func (mr *MockMetricStorageMockRecorder) UpdateGaugeMetric(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGaugeMetric", reflect.TypeOf((*MockMetricStorage)(nil).UpdateGaugeMetric), arg0, arg1, arg2)
}

// UpdateMetricsByBatch mocks base method.
func (m *MockMetricStorage) UpdateMetricsByBatch(arg0 context.Context, arg1 []models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetricsByBatch", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetricsByBatch indicates an expected call of UpdateMetricsByBatch.
func (mr *MockMetricStorageMockRecorder) UpdateMetricsByBatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetricsByBatch", reflect.TypeOf((*MockMetricStorage)(nil).UpdateMetricsByBatch), arg0, arg1)
}
